# api版本
apiVersion: v1
# 声明为 service 的配置
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-service-selector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30018
