apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-service-selector # 必须与 service 中的 spec.selector.app 保持一致
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app-service-selector
    spec:
      containers:
        - name: k8s-app
          image: alicfeng/k8s_app:v2.0
          ports:
            - containerPort: 80
