# api版本
apiVersion: v1
# 声明为 service 的配置
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: k8s-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
