apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: k8s-demo # 必须与 service 中的 spec.selector.app 保持一致
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo  # 必须与 service 中的 spec.selector.app 保持一致
    spec:
      containers:
        - name: demo-k8s
          image: fellah/gitbook:latest
          ports:
            - containerPort: 90
