apiVersion: v1
kind: Pod
metadata:
  name: nginx-port
spec:
  hostNetwork: true
  containers:
    - name: nginx-host
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 80
